version: "3"

tasks:
  build:
    desc: Build the Bauer and Bauer API binaries
    cmds:
      - go build -o bauer cmd/bauer/main.go
      - go build -o bauer-api cmd/app/main.go

  test:
    desc: Run all tests
    cmds:
      - go test --cover ./...

  lint:
    desc: Format code using gofmt
    cmds:
      - gofmt -w .

  run-server:
    desc: Run the API server locally
    cmds:
      - ./bauer-api --config config.json

  clean:
    desc: Clean up generated files
    cmds:
      - rm -rf bauer-output
      - rm -f bauer
      - rm -f bauer.log
      - rm -rf /tmp/gh* /tmp/tmp* /tmp/test-bauer-repo* || true

  run:
    desc: Clean up generated files, build and run Bauer server
    cmds:
      - task: clean
      - task: build
      - task: run-server